import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/header";
import { ThemeProvider } from "next-themes";
import Sidebar from "@/components/header/sidebar";
import ToastProvider from "@/providers/toast-provider";
import { auth } from "@/server/auth";
const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Product Management System",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          <ToastProvider />
          <Header session={session} />
          <main className="flex">
            <Sidebar />
            <section className="min-h-screen flex-1">{children}</section>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
